### ISSUE TITLE
Deprecated flags (Java 21)

### ISSUE THREAD

**Issue by Baterka** [Ovydux/MC-Startup-Script#10]
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option G1ConcRSHotCardLimit; support was removed in 21.0
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option G1ConcRefinementServiceIntervalMillis; support was removed in 20.0

You should probably mention that in the readme ;)

**Comment by Obydux** [comment]
> Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option G1ConcRSHotCardLimit; support was removed in 21.0 Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option G1ConcRefinementServiceIntervalMillis; support was removed in 20.0
> 
> You should probably mention that in the readme ;)

![image](https://github.com/user-attachments/assets/be18d2a4-7b6a-441d-a768-d3b96824c862)
